### ISSUE TITLE
Create script that removes all classes with names < 20 chars and that do not contain "Abstract", "Factory", "Bean" or "Holder" in name.

### ISSUE THREAD

**Issue by ibelfinger** [ibelfinger/open-source-ideas#4]

**Comment by SimunKaracic** [comment]
this regex should do it 
^(?:(?:(?:0?[13578]|1[02])(\/|-|\.)31)\1|(?:(?:0?[13-9]|1[0-2])(\/|-|\.)(?:29|30)\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:0?2(\/|-|\.)29\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:(?:0?[1-9])|(?:1[0-2]))(\/|-|\.)(?:0?[1-9]|1\d|2[0-8])\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$

Will make a pull request when test coverage reaches 90%

**Comment by ibelfinger** [comment]
Create .bash, .bat and perl script for that. Dockerize if possible.

**Comment by SimunKaracic** [comment]
Dockerfile for centos + perl regex cleaner



FROM scratch
MAINTAINER https://github.com/CentOS/sig-cloud-instance-images
ADD centos-7-docker.tar.xz /

LABEL name="CentOS Base Image" \
    vendor="CentOS" \
    license="GPLv2" \
    build-date="20161214"

FROM perl:5.20
COPY . /usr/src/open-source-ideas
WORKDIR /usr/src/open-source-ideas

CMD [ "perl", "./open-source-ideas-regex-factory.pl" ]

**Comment by ibelfinger** [comment]
@SimunKaracic Please write test for that
#3

**Comment by SimunKaracic** [comment]
Created self testing docker file: 

FROM scratch
MAINTAINER https://github.com/CentOS/sig-cloud-instance-images
ADD centos-7-docker.tar.xz /

LABEL name="CentOS Base Image" 
vendor="CentOS" 
license="GPLv2" 
build-date="20161214"

FROM perl:5.20
COPY . /usr/src/open-source-ideas
WORKDIR /usr/src/open-source-ideas

FROM the-best-test-ask-anyone:4.20
COPY: docker-testing-test
CMD ["python 'assertEquals("docker-testing-test-tester","the best")' "]

CMD [ "perl", "./open-source-ideas-regex-factory.pl" ]

**Comment by ibelfinger** [comment]
@SimunKaracic Also, test that docker container. Test coverage is currently only on 50%...

**Comment by SimunKaracic** [comment]
the container will not start if tests do not pass....

**Comment by ibelfinger** [comment]
Are you sure the tests are correct? Test the tests...

**Comment by SimunKaracic** [comment]
how bout you go and fix your own issue

**Comment by ibelfinger** [comment]
done. let's talk about your issue.

**Comment by SimunKaracic** [comment]
You mean our issue

**Comment by ibelfinger** [comment]
i mean your issue

**Comment by SimunKaracic** [comment]
Whose issue?
